LOG_TENSORBOARD = False

PADDING_IDX = 0
SEQUENCE_LENGTH = 27

WINDOW_SLIDE_LENGTH = 14
WINDOW_SLIDE_RANGE = 1

EMBED_DIMENSION = 700
EMBED_MAX_NORM = 1

LSTM_HIDDEN_SIZE = 128
LSTM_STACK_COUNT = 4

BATCH_LOG_INTERVAL = 200
VALID_PREDICTION_SAMPLE_RATE = 50
OPTIMIZER_ADAM_LR = 1.0
EPOCHS = 18
BATCH_SIZE = 64

TEMPERATURE = 1.0

SHUFFLE_DATA = True
APPLY_LR_SCHEDULER = False