LOG_TENSORBOARD = False

PADDING_IDX = 0
SEQUENCE_LENGTH = 99

WINDOW_SLIDE_LENGTH = 45
WINDOW_SLIDE_RANGE = 1

EMBED_DIMENSION = 64
EMBED_MAX_NORM = 1

LSTM_HIDDEN_SIZE = 16
LSTM_STACK_COUNT = 1

BATCH_LOG_INTERVAL = 200
VALID_PREDICTION_SAMPLE_RATE = 50
OPTIMIZER_ADAM_LR = 1.0
EPOCHS = 9
BATCH_SIZE = 64

TEMPERATURE = 1.0

SHUFFLE_DATA = True
APPLY_LR_SCHEDULER = True