LOG_TENSORBOARD = False

PADDING_IDX = 0
SEQUENCE_LENGTH = 512

EMBED_DIMENSION = 8
EMBED_MAX_NORM = 1

LSTM_HIDDEN_SIZE = 128
LSTM_STACK_COUNT = 2

BATCH_LOG_INTERVAL = 20
VALID_PREDICTION_SAMPLE_RATE = 5
OPTIMIZER_ADAM_LR = 1.0
EPOCHS = 9
BATCH_SIZE = 1

TEMPERATURE = 1.0

TRAIN_SPLIT = 0.9
VALID_SPLIT = 0.05
TEST_SPLIT = 0.05

SHUFFLE_DATA = True
APPLY_LR_SCHEDULER = True